### ISSUE TITLE
Sichtweise des Artikels

### ISSUE THREAD

**Issue by e1mo** [chaos-jetzt/ds_artikel_2020#1]
Aus welcher Sichtweise wollen wir den Artikel schreiben? Soll der Artikel **aus** unserer Sicht geschrieben werden oder über uns geschrieben werden? In Zeile 18 / 19 liest es sich mMn wie "Erwachsene haben sich beschlossen Jugendliche dazu anzuleiten sich besser zu vernetzen".  In Zeile 20 wird es sofort aus unserer Sicht geschrieben.

Ich persönlich bin dafür dass wir es konsequent aus unserer Sicht schreiben. Egal in welcher Form wir es schreiben sollten wir es aber konsequent überall durchführen.

**Comment by raketenlurch** [comment]
Ich wäre auch für aus unserer Sicht.

Dass das nicht ganz konsistent ist liegt daran, dass aus DS-Redaktion glaube ich schon mal jemensche gereviewt hat. Da würde ich aber davon ausgehen, dass wir das einfach wieder ändern können. :D

**Comment by e1mo** [comment]
Closed by #9
