### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by rugk** [chaos-jetzt/ds_artikel_2020#3]
Could we get a contributing guide? I e.g. don't know how to compile it. The "DSarticle" seems to be some custom thing.

**Comment by frommMoritz** [comment]
I think that our main focus should be the content itself. My understanding is that our .tex file will be part of a bigger Schleuderpackung.
So we should focus on the plaintext and edit that and the datenschleuder team will make the tex side fit.

**Comment by e1mo** [comment]
I think that our main focus should be the content itself. My understanding is that our .tex file will be part of a bigger Schleuderpackung.
So we should focus on the plaintext and edit that and the datenschleuder team will make the tex side fit.

(sorry for the spam, I was using the wrong account)
