### ISSUE TITLE
Zeit am Ende unklar

### ISSUE THREAD

**Issue by rugk** [chaos-jetzt/ds_artikel_2020#5]
> Auch ein erstes selbstorganisiertes Geekend im Göttinger Neotopia wurde für Ende Februar 2020 geplant und wird bis Redaktionsschluss vermutlich ausverkauft gewesen und noch vor Erscheinen der Ausgabe sehr gut gelaufen sein.

Das ist eine sehr umständlich formulierte Version für "Das Geekend war sehr gut.". Es verwirrt, dass man erst von Planung/Ausverkauf spricht und es im nächsten Moment doch schon gelaufen ist. Es wird also erst am Ende klar, welche Zeit(form) gemeint ist.

* dass es geplant wurde, ist klar (sobald es ausgeführt wurde); erwähnenswert ist das nur, wenn man bspw. zeitlich oder räumlich einen Bezug hat ("auf dem 36c3" o.ä.)
* ob es ausverkauft ist, wissen wir doch? also hinein schreiben (_nicht_ "vermutlich")
* allgemein steht wenig zum Geekend da, eher eine Vorstellung des Projektes allgemein -> hier könnte man noch bei Wunsch erweitern

Evt. so:

> Das erste [, noch auf dem 36c3 geplante, ??] selbstorganisierte Geekend im Göttinger Neotopia lief Ende Februar 2020 sehr erfolgreich geplant und war [nicht ganz] ausverkauft [dafür aber sehr \<adjektiv\>].

**Comment by e1mo** [comment]
> Das erste Geekend wurde bereits auf dem 36c3 erfolgreich geplant und fand ende Februar 2020 im Göttinger Neotopia statt. Das größtenteils durch den CCC finanzierte Wochenende war mit knapp 30 Besuchenden ausgebucht und bot eine gute Atmosphäre für ein effektives Findungstreffen.

**Comment by rugk** [comment]
@e1mo Das klingt doch gut. 👍 

Mag jemand pushen oder soll jmd. einen PR machen?

**Comment by e1mo** [comment]
Kann ich machen
