### ISSUE TITLE
"Wir wollen kaputte Strukturen im CCC reparieren – mit und ohne Lötkolben." mit rein nehmen

### ISSUE THREAD

**Issue by e1mo** [chaos-jetzt/ds_artikel_2020#7]
Beim Geekend kam das Motto

> Wir wollen kaputte Strukturen im CCC reparieren – mit und ohne Lötkolben

 auf und steht auch so im Protokoll. Ich fände es ganz cool das noch mit in den Artikel zu nehmen. Allerdings gehen in dem Artikel wir kaum in die Richtung eines älter werdenden Chaos, daher müsste einiges umgeschrieben werden. Oder vielleicht- wenn wir ein paar Ergebnisse vorzuweisen haben -nochmal einen weiteren Artikel schreiben?

**Comment by raketenlurch** [comment]
Ich frikel gerade noch bisschen dem Artikel rum. Versuche mal das einzubauen.

**Comment by n0emis** [comment]
closed by #9
